### ISSUE TITLE
Use more meaningful ID for a site

### ISSUE THREAD

**Issue by rschwietzke** [forcedotcom/comdagen#8]
Sites typically have IDs such as FoobarUS. The tool creates a site ID of 1 just now. Because this is also in the url of the site, it is a little off from reality.

**Comment by wundrian** [comment]
You aren't going for random site names, aren't you? Would using the name for the ID work, like `Site1`?

**Comment by rschwietzke** [comment]
I expected that the site name is used. Only make sure it is properly formatted aka most characters are not permitted. So maybe site name and id can be given in the config.
